APP_PASSWORD = "fh-ormeau-62002"

# Add &gid=SHEET_ID to export specific sheets
# To find the gid: open the sheet in browser, the URL will show gid=XXXXXXXXX
SHEET_CSV_URL_01 = "https://docs.google.com/spreadsheets/d/1IATDnuna_LPjMRzEBid8AP5vofpS-rv7rSz7c05tsto/export?format=csv&gid=0"
SHEET_CSV_URL_02 = "https://docs.google.com/spreadsheets/d/1IATDnuna_LPjMRzEBid8AP5vofpS-rv7rSz7c05tsto/export?format=csv&gid=1882978166"
